services:
  forti:
    build: .
    hostname: forti
    container_name: forti
    restart: unless-stopped
    volumes:
      - ./config/openfortivpn.config:/etc/openfortivpn/config:ro
      - ./config/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf:ro
    devices:
      - /dev/ppp:/dev/ppp
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - 127.0.0.1:8888:8888
